#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: POST

api:
    path: /api
    controller: App\Controller\AuthController::api
login:
    path: /api/login
    controller: App\Controller\AuthController::login

api_login_check:
    path: /api/login_check
    methods:  [POST]

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui

# api_authors:
#     path: /api/authors
#     controller: App\Controller\AuthorController::showAllAuthors

api_create_author:
    path: api/authors/new/edit
    controller: App\Controller\AuthorController::createAuthor

api_update_author:
    path: api/authors/{id}/edit
    controller: App\Controller\AuthorController::updateAuthor

api_delete_author:
    path: api/authors/{id}/delete
    controller: App\Controller\AuthorController::deleteAuthor